# Generated by Django 4.2 on 2023-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='อีเมลผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดปัญหา'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='done',
            field=models.BooleanField(default=False, verbose_name='แก้ปัญหาจบหรือยัง'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อผู้ถาม'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='สรุปปัญหานี้แก้อย่างไร'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ชื่อปัญหา(name)'),
        ),
    ]
